---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - ansible-lint --version
  - molecule --version
  - terraform --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - yamllint . -c .yamllint
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

Docker role from cookiecutter test:
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - molecule test -s default
  tags:
    - aws

AWS role from cookiecutter test:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
    - molecule test -s cloud-aws-direct
  tags:
    - aws

AZURE role from cookiecutter test:
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
    - molecule test -s cloud-azure-direct
  tags:
    - azure

EPC role from cookiecutter test:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - cookiecutter -f --no-input .
    - cd ansible-role-default_role
    - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated
