---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip install --upgrade ansible==2.8.* docker molecule==2.20.2
  - pip install git+https://github.com/ansible/ansible-lint.git
  - ansible --version
  - ansible-lint --version

script:
  - cookiecutter --no-input .
  - cd ansible-role-default_role
  - yamllint . -c .yamllint
  - ansible-lint . -c .ansible-lint
  - molecule test
